import { useState } from 'react';
import {
  Check,
  X,
  GitCompare,
  Clock,
  Download,
  Share2,
  MoreVertical,
  Shield,
  Sparkles,
  ChevronDown,
} from 'lucide-react';

interface CodeViewerProps {
  fileName: string;
  section: string;
}

export function CodeViewer({ fileName, section }: CodeViewerProps) {
  const [viewMode, setViewMode] = useState<'code' | 'diff'>('code');

  const codeContent = `package com.payment.service;

import org.springframework.stereotype.Service;
import org.springframework.retry.annotation.Retryable;
import org.springframework.retry.annotation.Backoff;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;

@Service
public class PaymentService {

    private final PaymentRepository repository;
    private final NotificationService notificationService;

    public PaymentService(PaymentRepository repository,
                         NotificationService notificationService) {
        this.repository = repository;
        this.notificationService = notificationService;
    }

    /**
     * Process payment with retry mechanism and JWT validation
     * AI-Generated: Added retry logic with exponential backoff
     * Security: Enhanced JWT validation per OWASP guidelines
     */
    @Retryable(
        value = { PaymentProcessingException.class },
        maxAttempts = 3,
        backoff = @Backoff(delay = 1000, multiplier = 2)
    )
    public PaymentResult processPayment(PaymentRequest request) {
        // Validate JWT token
        if (!validateJwtToken(request.getToken())) {
            throw new SecurityException("Invalid JWT token");
        }

        // Process payment logic
        Payment payment = repository.save(request.toPayment());

        // Send notification
        notificationService.sendConfirmation(payment);

        return PaymentResult.success(payment);
    }

    private boolean validateJwtToken(String token) {
        try {
            Jwts.parserBuilder()
                .setSigningKey(Keys.hmacShaKeyFor(jwtSecret.getBytes()))
                .build()
                .parseClaimsJws(token);
            return true;
        } catch (Exception e) {
            return false;
        }
    }
}`;

  const diffOldCode = `    public PaymentResult processPayment(PaymentRequest request) {
        // Process payment logic
        Payment payment = repository.save(request.toPayment());
        return PaymentResult.success(payment);
    }`;

  const diffNewCode = `    @Retryable(
        value = { PaymentProcessingException.class },
        maxAttempts = 3,
        backoff = @Backoff(delay = 1000, multiplier = 2)
    )
    public PaymentResult processPayment(PaymentRequest request) {
        // Validate JWT token
        if (!validateJwtToken(request.getToken())) {
            throw new SecurityException("Invalid JWT token");
        }

        // Process payment logic
        Payment payment = repository.save(request.toPayment());

        // Send notification
        notificationService.sendConfirmation(payment);

        return PaymentResult.success(payment);
    }`;

  return (
    <div className="flex-1 flex flex-col h-full bg-[#0A0F1E]">
      {/* Top Toolbar */}
      <div className="bg-[#111827] border-b border-white/10 p-4">
        <div className="flex items-start justify-between mb-4">
          <div className="flex-1">
            <div className="flex items-center gap-3 mb-2">
              <h2 className="text-lg font-semibold text-white">{fileName}</h2>
              <span className="px-2 py-1 bg-[#F59E0B]/10 text-[#F59E0B] text-xs rounded-full font-medium">
                PENDING REVIEW
              </span>
            </div>
            <div className="flex items-center gap-4 text-xs text-gray-400">
              <div className="flex items-center gap-1.5">
                <Sparkles className="w-3.5 h-3.5 text-[#6366F1]" />
                <span>Generated by: <span className="text-white font-medium">development_agent</span></span>
              </div>
              <span>•</span>
              <span>Iteration: <span className="text-white font-medium">2</span></span>
              <span>•</span>
              <div className="flex items-center gap-1.5">
                <Shield className="w-3.5 h-3.5 text-[#22C55E]" />
                <span>Security: <span className="text-[#22C55E] font-medium">PASS</span></span>
              </div>
              <span>•</span>
              <span>Deployment: <span className="text-white font-medium">staging-v12</span></span>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <div className="text-right mr-4">
              <p className="text-xs text-gray-400 mb-1">Confidence Score</p>
              <div className="flex items-center gap-2">
                <div className="w-20 h-1.5 bg-white/10 rounded-full overflow-hidden">
                  <div className="h-full bg-[#22C55E] rounded-full" style={{ width: '91%' }} />
                </div>
                <span className="text-sm font-bold text-white">91%</span>
              </div>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center justify-between">
          <div className="flex gap-2">
            <button
              onClick={() => setViewMode('code')}
              className={`px-3 py-1.5 text-sm font-medium rounded-lg transition-all ${
                viewMode === 'code'
                  ? 'bg-[#6366F1] text-white'
                  : 'bg-white/5 text-gray-400 hover:text-white hover:bg-white/10'
              }`}
            >
              Code
            </button>
            <button
              onClick={() => setViewMode('diff')}
              className={`px-3 py-1.5 text-sm font-medium rounded-lg transition-all flex items-center gap-1.5 ${
                viewMode === 'diff'
                  ? 'bg-[#6366F1] text-white'
                  : 'bg-white/5 text-gray-400 hover:text-white hover:bg-white/10'
              }`}
            >
              <GitCompare className="w-3.5 h-3.5" />
              Compare
            </button>
            <button className="px-3 py-1.5 text-sm font-medium bg-white/5 text-gray-400 hover:text-white hover:bg-white/10 rounded-lg transition-all flex items-center gap-1.5">
              <Clock className="w-3.5 h-3.5" />
              Timeline
            </button>
          </div>

          <div className="flex gap-2">
            <button className="px-4 py-1.5 bg-[#EF4444] hover:bg-[#DC2626] text-white text-sm font-medium rounded-lg transition-all flex items-center gap-1.5">
              <X className="w-4 h-4" />
              Reject
            </button>
            <button className="px-4 py-1.5 bg-[#F59E0B] hover:bg-[#D97706] text-white text-sm font-medium rounded-lg transition-all">
              Request Changes
            </button>
            <button className="px-4 py-1.5 bg-[#22C55E] hover:bg-[#16A34A] text-white text-sm font-medium rounded-lg transition-all flex items-center gap-1.5">
              <Check className="w-4 h-4" />
              Approve
            </button>
            <button className="p-1.5 bg-white/5 hover:bg-white/10 text-gray-400 rounded-lg transition-all">
              <MoreVertical className="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>

      {/* AI Summary Banner */}
      <div className="bg-gradient-to-r from-[#6366F1]/10 to-[#8B5CF6]/10 border-b border-[#6366F1]/20 p-3">
        <div className="flex items-start gap-3">
          <div className="p-2 bg-[#6366F1]/20 rounded-lg">
            <Sparkles className="w-4 h-4 text-[#6366F1]" />
          </div>
          <div className="flex-1">
            <p className="text-sm font-medium text-white mb-1">AI-Generated Changes Summary</p>
            <p className="text-xs text-gray-300">
              Added retry mechanism with exponential backoff (3 attempts, 1s delay). Enhanced JWT validation following OWASP best practices. Integrated notification service for payment confirmations.
            </p>
          </div>
          <button className="text-xs text-[#6366F1] hover:text-[#8B5CF6] font-medium">
            Details
          </button>
        </div>
      </div>

      {/* Code/Diff Content */}
      <div className="flex-1 overflow-hidden">
        {viewMode === 'code' ? (
          <div className="h-full overflow-auto bg-[#0A0F1E] p-6 font-mono text-sm">
            <pre className="text-gray-300 leading-relaxed">
              {codeContent.split('\n').map((line, index) => (
                <div key={index} className="flex hover:bg-white/5">
                  <span className="inline-block w-12 text-right pr-4 text-gray-600 select-none">
                    {index + 1}
                  </span>
                  <span className="flex-1">
                    {line.includes('AI-Generated') ? (
                      <span className="text-[#6366F1]">{line}</span>
                    ) : line.includes('Security:') ? (
                      <span className="text-[#22C55E]">{line}</span>
                    ) : line.includes('@Retryable') ||
                      line.includes('validateJwtToken') ||
                      line.includes('SecurityException') ? (
                      <span className="bg-[#22C55E]/10 text-[#22C55E]">{line}</span>
                    ) : (
                      line
                    )}
                  </span>
                </div>
              ))}
            </pre>
          </div>
        ) : (
          <div className="h-full overflow-auto bg-[#0A0F1E]">
            <div className="grid grid-cols-2 h-full">
              {/* Old Code */}
              <div className="border-r border-white/10 bg-[#EF4444]/5">
                <div className="bg-[#EF4444]/20 border-b border-[#EF4444]/30 px-4 py-2">
                  <span className="text-xs font-medium text-[#EF4444]">OLD (Iteration 1)</span>
                </div>
                <div className="p-6 font-mono text-sm">
                  <pre className="text-gray-400 leading-relaxed">
                    {diffOldCode.split('\n').map((line, index) => (
                      <div key={index} className="flex">
                        <span className="inline-block w-12 text-right pr-4 text-gray-600 select-none">
                          {index + 1}
                        </span>
                        <span className="flex-1 line-through opacity-60">{line}</span>
                      </div>
                    ))}
                  </pre>
                </div>
              </div>

              {/* New Code */}
              <div className="bg-[#22C55E]/5">
                <div className="bg-[#22C55E]/20 border-b border-[#22C55E]/30 px-4 py-2">
                  <span className="text-xs font-medium text-[#22C55E]">NEW (Iteration 2)</span>
                </div>
                <div className="p-6 font-mono text-sm">
                  <pre className="text-gray-300 leading-relaxed">
                    {diffNewCode.split('\n').map((line, index) => (
                      <div key={index} className="flex">
                        <span className="inline-block w-12 text-right pr-4 text-gray-600 select-none">
                          {index + 1}
                        </span>
                        <span className="flex-1 bg-[#22C55E]/10">{line}</span>
                      </div>
                    ))}
                  </pre>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
